SELECT WAREHOUSE, PO_NUMBER, DATE_ORDERED, QUANTITY, 
CASE
	WHEN QUANTITY >= 5 THEN 'MEETS FREIGHT ALLOWED'
	WHEN QUANTITY >= 1 THEN 'FREIGHT MUST BE PAID'
	ELSE 'QUANTITY NEEDED TO PLACE ORDER'
END AS Freight_Allowance
FROM General_air_Oct23
;


